services:
  physical-library:
    build: ./backend
    container_name: physical-library
    ports:
      - "8099:8099"
    volumes:
      - ./data:/data
      - ./exports:/exports
    env_file:
      - .env
    restart: unless-stopped
